apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunproject
  labels:
    app: sunproject
  namespace: aka-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sunproject
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sunproject
    spec:
      containers:
      - image: onyeechris/sunproject:v19
        imagePullPolicy: Always
        name: sunproject
        ports:
        - containerPort: 80
          protocol: TCP
      #   volumeMounts:
      #   - name: nginx-config-volume
      #     mountPath: /etc/nginx/conf.d/default.conf
      #     subPath: nginx.conf
      # volumes:
      # - name: nginx-config-volume
      #   configMap:
      #     name: nginx-config
