apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: aka-ns
data:
  nginx.conf: |
    server {
        listen 3000;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
