server {
    listen 3000;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Serve static assets from the /assets/ directory
    location /assets/ {
        root /usr/share/nginx/html;
    }
}
