apiVersion: v1
kind: Service
metadata:
  name: ecsdemo-nodejs
spec:
  type: NodePort
  selector:
    app: ecsdemo-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007  # Ensure this port is within the 30000-32767 range
