apiVersion: v1
kind: Service
metadata:
  name: sunproject
spec:
  type: NodePort
  selector:
    app: sunproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # Ensure this port is within the 30000-32767 range
